In [1]:
import numpy as np

def gauss_elimination_no_pivoting(A, b):
    n = len(A)
    # Convert to augmented matrix
    Ab = np.hstack((A, b.reshape(-1, 1)))

    # Forward elimination
    for i in range(n):
        if Ab[i, i] == 0:
            raise ValueError("Zero pivot encountered without pivoting.")
        for j in range(i+1, n):
            factor = Ab[j, i] / Ab[i, i]
            Ab[j, i:] -= factor * Ab[i, i:]

    # Back substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (Ab[i, -1] - np.dot(Ab[i, i+1:n], x[i+1:n])) / Ab[i, i]

    return x

# Example usage
A = np.array([[2, -1, 1], [3, 2, -4], [1, 1, -1]], dtype=float)
b = np.array([1, 7, 2], dtype=float)

solution = gauss_elimination_no_pivoting(A, b)
print("Solution without pivoting:", solution)

Solution without pivoting: [ 1.  0. -1.]


In [2]:
import numpy as np

def gauss_elimination_partial_pivoting(A, b):
    n = len(A)
    # Convert to augmented matrix
    Ab = np.hstack((A, b.reshape(-1, 1)))

    # Forward elimination with partial pivoting
    for i in range(n):
        # Partial pivoting: find the max element in the current column
        max_row = np.argmax(np.abs(Ab[i:n, i])) + i
        if Ab[max_row, i] == 0:
            raise ValueError("Singular matrix detected.")

        # Swap rows
        if max_row != i:
            Ab[[i, max_row]] = Ab[[max_row, i]]

        # Elimination
        for j in range(i+1, n):
            factor = Ab[j, i] / Ab[i, i]
            Ab[j, i:] -= factor * Ab[i, i:]

    # Back substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (Ab[i, -1] - np.dot(Ab[i, i+1:n], x[i+1:n])) / Ab[i, i]

    return x

# Example usage
A = np.array([[0.3, 2.6, 1.3], [8.3, 8.2, 5.6], [12.7, 3.5, 7.4]], dtype=float)
b = np.array([7.65, 43.17, 49.68], dtype=float)
#A = np.array([[2, -1, 1], [3, 2, -4], [1, 1, -1]], dtype=float)
#b = np.array([1, 7, 2], dtype=float)

solution = gauss_elimination_partial_pivoting(A, b)
print("Solution with partial pivoting:", solution)

Solution with partial pivoting: [2.1 1.5 2.4]


LU decomposition

In [1]:
import numpy as np

def lu_gauss_elimination(A):
    n = len(A)
    L = np.eye(n)  # Initialize L as identity matrix
    U = A.astype(float)  # Copy A to U

    for i in range(n):
        for j in range(i+1, n):
            factor = U[j, i] / U[i, i]
            L[j, i] = factor
            U[j] = U[j] - factor * U[i]

    return L, U


def lu_crout(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.eye(n)

    for i in range(n):
        for j in range(i, n):
            L[j, i] = A[j, i] - sum(L[j, k] * U[k, i] for k in range(i))

        for j in range(i+1, n):
            U[i, j] = (A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))) / L[i, i]

    return L, U


# Example Usage
A = np.array([[4, -2, 4], [-2, 10, -2], [4, -2, 6]], dtype=float)

L_gauss, U_gauss = lu_gauss_elimination(A)
L_crout, U_crout = lu_crout(A)

print("LU Decomposition using Gauss Elimination:")
print("L:")
print(L_gauss)
print("U:")
print(U_gauss)

print("\nLU Decomposition using Crout's Method:")
print("L:")
print(L_crout)
print("U:")
print(U_crout)

LU Decomposition using Gauss Elimination:
L:
[[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [ 1.   0.   1. ]]
U:
[[ 4. -2.  4.]
 [ 0.  9.  0.]
 [ 0.  0.  2.]]

LU Decomposition using Crout's Method:
L:
[[ 4.  0.  0.]
 [-2.  9.  0.]
 [ 4.  0.  2.]]
U:
[[ 1.  -0.5  1. ]
 [ 0.   1.   0. ]
 [ 0.   0.   1. ]]
